import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import SidebarWrapper from "./SidebarWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> 
      <body>
        <div className={`flex ${geistSans.variable} ${geistMono.variable} antialiased cursor-defaultbg-gray-900`}>
          <SidebarWrapper/>
        <main className="flex-1 bg-gray-100 min-h-screen">
          {children}
        </main>
         <Toaster />
        </div>
      </body>
    </html>
  );
}
